name: QA Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20] # Test against multiple Node.js versions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Upload Coverage Report (Optional)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
