name: QA Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  qa:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20] # Use Node.js versions that support structuredClone

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npx eslint .
